  
  ./configure --prefix=/usr             \
              $OPTS			&&
  make                                  &&
  prepare_install                       &&
  make    install                           
