--- Makefile.linux	2003-02-06 20:26:19.000000000 -0600
+++ Makefile.linux	2003-04-15 23:59:59.000000000 -0600
@@ -41,6 +41,7 @@
 # **** End of SMP/MODVERSIONS detection
 
 MODS =		gamma.o tdfx.o r128.o radeon.o
+MODS2INSTALL =		gamma.o tdfx.o r128.o radeon.o
 LIBS =
 
 DRMTEMPLATES =	drm_auth.h drm_bufs.h drm_context.h drm_dma.h drm_drawable.h \
@@ -306,3 +307,7 @@
 		if [ -L $$i ]; then (set -x; rm -f $$i); fi; \
 	done
 
+install::
+	@for i in $(MODS2INSTALL); do \
+		if [ -f /lib/modules/$(VERSION)/kernel/drivers/char/drm/$$i ]; then (cp -f $$i /lib/modules/$(VERSION)/kernel/drivers/char/drm); fi; \
+	done
