(
  . /usr/GNUstep/System/Makefiles/GNUstep.sh  &&
  ./configure                                 &&
  make                                        &&
  prepare_install                             &&
  make install
) >$C_FIFO 2>&1
