EXEPATH=/usr/bin
MANPATH=/usr/man/man1

make                            &&
make	doc			&&
prepare_install                 &&
chmod	755	clara selthresh
chmod	644	doc/*
cp  clara selthresh	$EXEPATH
cp  doc/clara.1		$MANPATH
