  ./configure --prefix=/usr                 \
              --dynamic	                    \
              $OPTS                         &&
  make                                      &&
  prepare_install                           &&
  make install
